apiVersion: apps/v1
kind: Deployment
metadata:
  name: ankit-deployment
  labels:
    app: nginx
spec:
  replicas: 5 # You can adjust the number of Nginx instances as needed
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest # It's recommended to use a specific version in production, e.g., nginx:1.25.3
        ports:
        - containerPort: 80 # Nginx typically listens on port 80 for HTTP traffic

---
apiVersion: v1
kind: Service
metadata:
  name: ankit-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on
      targetPort: 80 # The port Nginx is listening on inside the container
  type: NodePort # Use NodePort for local development/on-prem, ClusterIP for internal, LoadBalancer for cloud exposure
